### ISSUE TITLE
How to call plugin w/o an element

### ISSUE THREAD

**Issue by thedamon** [jquery-boilerplate/jquery-boilerplate#104]
I'm trying to create a plugin that can be called without an element. 

I understand I should use `$.extend` to do that, but I don't see how to do it with the boilerplate as written.. it's already using extend but my plugin isn't available as a $.myPluginName() and I don't quite follow where I need to change to make sure it's extending the default $ object

**Comment by vovan47** [comment]
I have the same problem. Did you handled it?

**Comment by heldr** [comment]
This is not a pattern though 
```js
//...
function Plugin ( options ) {
  //...
}
//...
// do not use $.fn
$[ pluginName ] = function ( options ) {
  return new Plugin( options );
};
```
