### ISSUE TITLE
Consider create a grunt template

### ISSUE THREAD

**Issue by dcdeiv** [jquery-boilerplate/jquery-boilerplate#115]
It would be awesome if this repo was a [grunt template](http://gruntjs.com/project-scaffolding) because it would be really easy and super fast to install **jquery-boilerplate**:

```shell
grunt-init jquery-boilerplate
```

This command would initialize a jquery-boilerplate project withouth the hassle of download, unzip, copy and paste all files. :)

**Comment by heldr** [comment]
Hello,

Thank you for the suggesttion, but we already have a yeoman generator that does pretty much the same thing https://github.com/jquery-boilerplate/generator-jquery-boilerplate
