### ISSUE TITLE
unit testing boilerplate?

### ISSUE THREAD

**Issue by radiovisual** [jquery-boilerplate/jquery-boilerplate#119]
any chance this repo would be open to adding a unit testing boilerplate to give the boilerplate users a starting point (or recipes) for unit testing their plugins created with the boilerplate?

**Comment by radiovisual** [comment]
Or perhaps a unit testing pattern could be added as a pattern on [jquery-boilerplate/jquery-patterns](https://github.com/jquery-boilerplate/jquery-patterns)? ...

**Comment by zenorocha** [comment]
Have you seen the `test` folder? https://github.com/jquery-boilerplate/jquery-boilerplate/blob/master/test/spec/jquery.boilerplate.spec.js

**Comment by radiovisual** [comment]
Ah. I missed all that. It is helpful. Thanks.

**Comment by zenorocha** [comment]
;)
