### ISSUE TITLE
Public functions

### ISSUE THREAD

**Issue by adyz** [jquery-boilerplate/jquery-boilerplate#121]
How can I make a function that I can call like this

`var myPluginInstance = $('.element').myPlugin()`
`myPluginInstance.close()`

Thanks

**Comment by zenorocha** [comment]
https://github.com/jquery-boilerplate/jquery-boilerplate/wiki/Extending-jQuery-Boilerplate#allow-access-to-public-prototype-methods

**Comment by adyz** [comment]
Hi @zenorocha,

Thanks for your answer, it dose not look exactly on how I wished, but I think this is standard, just a few plugins use the syntax above.

**Comment by zenorocha** [comment]
Feel free to use whatever feels best for your. You may also like [jquery-patterns](https://github.com/jquery-boilerplate/jquery-patterns).
