### ISSUE TITLE
Max level not labeled

### ISSUE THREAD

**Issue by cunha1973** [jquery-boilerplate/jquery-boilerplate#129]
![image](https://user-images.githubusercontent.com/7191580/66078870-441a9480-e539-11e9-8ed3-0fe740fbda83.png)

During some tests I noticed some data missing (max).
Here is the data:

[{"date":"2019-08-04","count":"3"},{"date":"2019-08-06","count":"8"},{"date":"2019-08-07","count":"3"},{"date":"2019-08-16","count":"1"},{"date":"2019-08-20","count":"1"},{"date":"2019-08-22","count":"1"},{"date":"2019-08-23","count":"1"},{"date":"2019-08-29","count":"1"},{"date":"2019-09-28","count":"1"},{"date":"2019-10-01","count":"2"},{"date":"2019-10-02","count":"1"}]

**Comment by SeBassTian23** [comment]
This is the wrong Repo, you probably found the issue [here](https://github.com/SeBassTian23/CalendarHeatmap). The recent update (1.1.0) should fix the issue you are describing.
