### ISSUE TITLE
How to extend the plugin?

### ISSUE THREAD

**Issue by bini7a** [jquery-boilerplate/jquery-boilerplate#96]
Actually I'm very beginner to plugin development and trying to write a plugin.

Now, I'm stumbled that how should I start writing?

Suppose, I've set up defaults values like this:

defaults = {
   myProperty: undefined
};

And now I can use it like this:

.myPluginName({myProperty:10}) 

Now, I tried to console the myProperty value within the $.fn method which outputs "undefined":

$.fn[ pluginName ] = function ( options ) {
this.each(function(){
  console.log(defaults.myProperty);//logs undefined
});
return this;
};

And now if I use inside Plugin function then outputs "10" which is what I want:

function Plugin ( element, options ) {
    this.element = element;
    this.settings = $.extend( {}, defaults, options );
    this._defaults = defaults;
    this._name = pluginName;
   console.log(this.settings.myProperty);//logs 10
    this.init();
}

So, actually, how should I start writing a plugin?

**Comment by fntneves** [comment]
This line of code allows developer to override your defaults.
```
this.settings = $.extend( {}, defaults, options );
````

That's why you've got 10 on last case.
