### ISSUE TITLE
Regarding testing of the JQUERY plugin

### ISSUE THREAD

**Issue by settysreekanth** [jquery-boilerplate/jquery-boilerplate#97]
Hi, This is not an issue, however -May I know if there are any Unit Testing samples written for testing this plugin?

**Comment by arthurvr** [comment]
https://github.com/jquery-boilerplate/jquery-boilerplate/pull/76 is upcoming.

**Comment by heldr** [comment]
Coming in [4.0](https://github.com/jquery-boilerplate/jquery-boilerplate/tree/4.0.0)

**Comment by heldr** [comment]
v4 was published with test examples
